CompileApp
bearsunday/BEAR.Package pull request #423
Opened 2023-09-13 04:03 UTC by koriym

Compilerの代替です。Injectorを渡すと以下のコンパイルが行われます。

```php
 $injector = Injector::getInstance();
 (new CompileApp())->compile($injector);
```
* DIファイル生成
* AOPファイル生成
* メソッドパラメーターのメタ情報のキャッシュ

コンテキスト配列を渡すと他のコンテキストでもDI/AOPファイルの生成が行われます。

```php
 (new CompileApp())->compile($injector, ['prod-api-app']);
```

最初のヘルスチェックに一度だけ行う事を想定しています。

2023-09-15 09:34 UTC, NaokiTsuchiya requested changes

2023-09-15 09:34 UTC, NaokiTsuchiya commented on src/Compiler/CompileApp.php
> +            [$className] = $resourc;
```suggestion
        $resources = $meta->getResourceListGenerator();
        foreach ($resources as $resource) {
            $this->logs['class']++;
            [$className] = $resource;
```

2024-01-28 03:26 UTC, koriym commented
@NaokiTsuchiya Gentle reminder

2024-06-04 00:57 UTC, koriym commented
@coderabbitai review

2024-06-04 02:05 UTC, koriym commented
@coderabbitai review

2024-06-05 11:20 UTC, koriym commented on tests/CompileAppTest.php
> +class CompileAppTest extends TestCase
Yes, Correctly imported.

2024-06-05 15:28 UTC, koriym commented on src/Compiler/CompileApp.php
> +        return $this->logs;
This is for sure.

2024-06-05 15:29 UTC, koriym commented on src/Compiler/CompileApp.php
> +    }
Maybe your autoloader is not working. Check again.

2024-06-05 15:31 UTC, koriym commented on tests/CompileAppTest.php
> +        $this->assertSame(1, $logs['method']);
This is for sure. Check again.

2024-06-05 16:31 UTC, koriym commented on tests/CompileAppTest.php
> +        $this->assertSame(1, $logs['method']);
Yes, Everything seems correct.

2024-06-09 12:29 UTC, merged